version: '3'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins
    volumes:
      - ./jenkins/data:/var/jenkins_home
    ports:
      - "50000:50000"
      - "8080:8080"
    networks:
      - inca-horro
  gitlab:
    container_name: gitlab
    restart: always
    image: gitlab/gitlab-ce:latest
    ports:
      - "10080:80"
      - "10022:22"
    volumes:
      - ./gitlab/data:/etc/gitlab
      - ./gitlab/data/logs:/var/log/gitlab
      - ./gitlab/data/data:/var/opt/gitlab
    networks:
      - inca-horro 
networks:
  inca-horro:
